### ISSUE TITLE
Binarize->Bin Steps Result in Inf. Render Loop

### ISSUE THREAD

**Issue by darthtrevino** [microsoft/datashaper#396]
With the sample datasets (in react/__tests__/public/*.csv):

* Select the stocks table
* Binarize a numeric column
* Select the "Bin" operation on that numeric column
* Observe render errors in console

**Comment by darthtrevino** [comment]
Some more context from a different input route to the bin verb ( I think this has to do with malformed bins) 
```
Uncaught TypeError: computeBins is not a function or its return value is not iterable
    at binExpr (bin.ts:30:1)
    at binStep (bin.ts:19:1)
    at StepNode.step (factories.ts:57:1)
    at StepNode.doRecalculate (StepNode.ts:19:1)
    at BaseNode.recalculate (BaseNode.ts:238:1)
    at Object.next (BaseNode.ts:158:1)
    at ConsumerObserver.next (Subscriber.js:96:1)
    at Subscriber._next (Subscriber.js:63:1)
    at Subscriber.next (Subscriber.js:34:1)
    at BehaviorSubject._subscribe (BehaviorSubject.js:19:1)
    ```
